import { describe, it, expect, vi, beforeEach } from 'vitest';
import { getSupabaseAdminClient } from '../../lib/supabase';
import { checkWorkspacePermission } from '../../lib/auth';
import { 
  upsertOrganization, 
  setWorkspaceModuleType, 
  seedWorkspaceKCulture, 
  getDomainPacks, 
  getCulturalConcepts,
  getCulturalOpportunities
} from '../../app/actions/kculture';
import { runKCultureEvaluation } from '../../app/actions/kculture-eval';

vi.mock('../../lib/supabase', () => ({
  getSupabaseAdminClient: vi.fn(),
}));

vi.mock('../../lib/auth', () => ({
  checkWorkspacePermission: vi.fn(),
}));

const createMockQueryBuilderForTable = (table: string, domainPackId: string) => {
  const qb: any = {
    eq: vi.fn().mockImplementation(() => qb),
    in: vi.fn().mockImplementation(() => qb),
    select: vi.fn().mockImplementation(() => qb),
    insert: vi.fn().mockImplementation(() => qb),
    update: vi.fn().mockImplementation(() => qb),
    upsert: vi.fn().mockImplementation(() => qb),
    maybeSingle: vi.fn().mockImplementation(async () => {
      if (table === 'domain_packs') {
        return { data: { id: domainPackId, slug: "k-beauty", name: "Mock Pack", default_qbs_templates: [{ question_text: "Q1", intent_type: "informational", required_concepts: ["C1"] }] }, error: null };
      }
      return { data: { id: "11111111-1111-4111-8111-111111111111" }, error: null };
    }),
    single: vi.fn().mockImplementation(async () => {
      if (table === 'domain_packs') {
        return { data: { id: domainPackId, name: "Mock Pack", slug: "k-beauty", default_qbs_templates: [{ question_text: "Q1", intent_type: "informational", required_concepts: ["C1"] }] }, error: null };
      }
      if (table === 'concept_fidelity_snapshots') {
        return { data: { id: "11111111-1111-4111-8111-111111111111", cross_cultural_resonance: 0.91, commercial_transferability: 0.88 }, error: null };
      }
      return { data: { id: "11111111-1111-4111-8111-111111111111" }, error: null };
    }),
    then: vi.fn().mockImplementation((onFulfilled) => {
      let data: any[] = [];
      if (table === 'domain_packs') {
        data = [{ id: domainPackId, slug: 'k-beauty', name: 'K-Beauty Standard Pack', default_qbs_templates: [{ question_text: "Q1", intent_type: "informational", required_concepts: ["C1"] }] }];
      } else if (table === 'cultural_concepts') {
        data = [{ id: "c-1", concept_id: "C1", preferred_label: { ko: "개념", en: "Concept" }, concept_type: "ingredients", status: "active", definition: "Concept Def", preferred_label_ko: "개념", preferred_label_en: "Concept" }];
      } else if (table === 'probe_questions') {
        data = [{ id: "q-1", question_text: "Q1", required_concepts: ["C1"] }];
      } else if (table === 'probe_runs') {
        data = [{ id: "pr-1", probe_question_id: "q-1" }];
      } else if (table === 'cultural_opportunities') {
        data = [{ id: "o-1", opportunity_type: 'product', title: 'Premium K-Beauty Treatment', linked_concepts: ["C1"] }];
      }
      return Promise.resolve(onFulfilled({ data, error: null }));
    }),
  };
  return qb;
};

describe('K-Culture Intelligence OS E2E Walkthrough Integration Tests', () => {
  const workspaceId = '11111111-1111-4111-8111-111111111111';
  const domainPackId = '11111111-1111-4111-8111-222222222222';
  let mockSupabase: any;

  beforeEach(() => {
    vi.clearAllMocks();
    vi.mocked(checkWorkspacePermission).mockResolvedValue(true);
    
    mockSupabase = {
      from: vi.fn().mockImplementation((table: string) => {
        return createMockQueryBuilderForTable(table, domainPackId);
      })
    };
    (getSupabaseAdminClient as any).mockReturnValue(mockSupabase);
  });

  it('should successfully execute a full E2E walkthrough flow', async () => {
    // 1. Create Organization
    const org = await upsertOrganization({
      name: "Acme K-Culture Corp",
      slug: "acme-kculture-corp"
    });
    expect(org).toBeDefined();
    expect(org.id).toBeDefined();

    // 2. Set Workspace module type to hybrid (Brand + K-Culture coexisting)
    const ws = await setWorkspaceModuleType(workspaceId, 'hybrid');
    expect(ws).toBeDefined();

    // 3. Seed Workspace K-Culture Domain Packs and Concepts
    const seedRes = await seedWorkspaceKCulture(workspaceId);
    expect(seedRes.success).toBe(true);

    // 4. Load seeded domain packs
    const packs = await getDomainPacks(workspaceId);
    expect(packs).toHaveLength(1);
    expect(packs[0].slug).toBe('k-beauty');

    // 5. Run a complete baseline evaluation run
    const snap = await runKCultureEvaluation(workspaceId, domainPackId, 'baseline');
    expect(snap).toBeDefined();
    expect(snap.cross_cultural_resonance).toBeDefined();
    expect(snap.commercial_transferability).toBeDefined();

    // 6. Get opportunities automatically generated by OpportunityEngine
    const opps = await getCulturalOpportunities(workspaceId);
    expect(opps).toHaveLength(1);
    expect(opps[0].opportunity_type).toBe('product');
  });
});
