import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { getAIProvider } from '../../lib/ai/ai-provider';
import { getEmbeddingProvider } from '../../lib/ai/embedding-provider';

describe('AI & Embedding Provider abstraction tests (Phase 1)', () => {
  const originalMode = process.env.AI_PROVIDER_MODE;

  beforeEach(() => {
    process.env.AI_PROVIDER_MODE = 'mock';
  });

  afterEach(() => {
    process.env.AI_PROVIDER_MODE = originalMode;
  });

  it('should return MockProvider when AI_PROVIDER_MODE is mock', () => {
    const provider = getAIProvider();
    expect(provider.constructor.name).toBe('MockProvider');
  });

  it('should return MockEmbeddingProvider when AI_PROVIDER_MODE is mock', () => {
    const provider = getEmbeddingProvider();
    expect(provider.constructor.name).toBe('MockEmbeddingProvider');
  });

  it('should return deterministic text generated by MockProvider', async () => {
    const provider = getAIProvider();
    const prompt = 'retinol insight';
    const text = await provider.generateText(prompt);
    expect(text).toContain('AEO Readiness Score');
  });

  it('should parse structured output in mock mode', async () => {
    const provider = getAIProvider();
    const result = await provider.generateStructuredOutput<{ claims: string[] }>('niacinamide skincare', {});
    expect(result.claims).toBeDefined();
    expect(result.claims.length).toBe(2);
    expect(result.claims[0]).toContain('Niacinamide');
  });

  it('should produce 768-dimensional unit embeddings in mock mode', async () => {
    const provider = getEmbeddingProvider();
    const vector = await provider.embed('PureBarrier Clinically tested Retinol');
    
    expect(vector.length).toBe(768);
    
    // Check if it is normalized to unit length: sum of squares = 1
    const sumSquares = vector.reduce((sum, val) => sum + val * val, 0);
    expect(sumSquares).toBeCloseTo(1.0, 3);
  });
});
